# Generated by Django 5.0.2 on 2024-08-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_monthyl_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monthyl_Attendance',
        ),
    ]
