# Generated by Django 5.0.2 on 2024-08-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_monthyl_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('edit_marks', 'Can edit marks for their subjects')]},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='course',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='monthyl_attendance',
            name='month',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='monthyl_attendance',
            name='percentage',
            field=models.CharField(max_length=3),
        ),
    ]
